In [1]:
import pandas as pd
import sqlite3

# Load your clean CSV
df = pd.read_csv(r'C:\Users\abdin\Desktop\Decision Analysist\Chapter 1 Projects\East African Countries Development Indicators\Data\EAC_Development_Indicators_Clean.csv')

# Create an in-memory database
conn = sqlite3.connect(':memory:')

# Load the dataframe into the database as a table
df.to_sql('eac_indicators', conn, index=False, if_exists='replace')

print("Database ready. Rows loaded:", len(df))

Database ready. Rows loaded: 600

In [3]:
query1 = """
SELECT "Country Name", "Year", "Value"
FROM eac_indicators
WHERE "Series Name" = 'GDP per capita (current LCU)'
AND "Country Name" IN ('Somalia, Fed. Rep.', 'Rwanda')
ORDER BY "Country Name", "Year"
"""

result1 = pd.read_sql_query(query1, conn)
result1

          Country Name  Year         Value
0               Rwanda  2010  3.461610e+05
1               Rwanda  2011  3.908798e+05
2               Rwanda  2012  4.341944e+05
3               Rwanda  2013  4.558294e+05
4               Rwanda  2014  4.947384e+05
5               Rwanda  2015  5.283759e+05
6               Rwanda  2016  5.743150e+05
7               Rwanda  2017  6.305685e+05
8               Rwanda  2018  6.645691e+05
9               Rwanda  2019  7.285201e+05
10              Rwanda  2020  7.345320e+05
11              Rwanda  2021  8.201086e+05
12              Rwanda  2022  1.005034e+06
13              Rwanda  2023  1.191461e+06
14              Rwanda  2024  1.317673e+06
15  Somalia, Fed. Rep.  2010  6.854387e+06
16  Somalia, Fed. Rep.  2011  7.051974e+06
17  Somalia, Fed. Rep.  2012  7.886498e+06
18  Somalia, Fed. Rep.  2013  7.586222e+06
19  Somalia, Fed. Rep.  2014  8.687390e+06
20  Somalia, Fed. Rep.  2015  9.917534e+06
21  Somalia, Fed. Rep.  2016  1.063125e+07
22  Somalia, Fed. Rep.  2017  1.180160e+07
23  Somalia, Fed. Rep.  2018  1.220459e+07
24  Somalia, Fed. Rep.  2019  1.353377e+07
25  Somalia, Fed. Rep.  2020  1.334844e+07
26  Somalia, Fed. Rep.  2021  1.429690e+07
27  Somalia, Fed. Rep.  2022  1.537882e+07
28  Somalia, Fed. Rep.  2023  1.625041e+07
29  Somalia, Fed. Rep.  2024  1.770127e+07

In [4]:
query2 = """
SELECT "Country Name", "Year", "Value"
FROM eac_indicators
WHERE "Series Name" = 'Population, total'
AND "Country Name" = 'Congo, Dem. Rep.'
AND "Year" BETWEEN 2020 AND 2024
ORDER BY "Year"
"""

result2 = pd.read_sql_query(query2, conn)
result2

       Country Name  Year        Value
0  Congo, Dem. Rep.  2020   95989998.0
1  Congo, Dem. Rep.  2021   99148932.0
2  Congo, Dem. Rep.  2022  102396968.0
3  Congo, Dem. Rep.  2023  105789731.0
4  Congo, Dem. Rep.  2024  109276265.0

In [5]:
query3 = """
SELECT "Country Name", "Year", "Value"
FROM eac_indicators
WHERE "Series Name" = 'Inflation, consumer prices (annual %)'
AND "Country Name" = 'Somalia, Fed. Rep.'
ORDER BY "Year"
"""

result3 = pd.read_sql_query(query3, conn)
result3

          Country Name  Year Value
0   Somalia, Fed. Rep.  2010  None
1   Somalia, Fed. Rep.  2011  None
2   Somalia, Fed. Rep.  2012  None
3   Somalia, Fed. Rep.  2013  None
4   Somalia, Fed. Rep.  2014  None
5   Somalia, Fed. Rep.  2015  None
6   Somalia, Fed. Rep.  2016  None
7   Somalia, Fed. Rep.  2017  None
8   Somalia, Fed. Rep.  2018  None
9   Somalia, Fed. Rep.  2019  None
10  Somalia, Fed. Rep.  2020  None
11  Somalia, Fed. Rep.  2021  None
12  Somalia, Fed. Rep.  2022  None
13  Somalia, Fed. Rep.  2023  None
14  Somalia, Fed. Rep.  2024  None

In [ ]:
query4 = """

SELECT "Country Name", "Year", "Value"
FROM eac_indicators
WHERE "Series Name" = 'Unemployment, total (% of total labor force) (national estimate)'
AND "Country Name" = 'Uganda'
ORDER BY "Year"
"""

result4 = pd.read_sql_query(query4, conn)
result4

   Country Name  Year  Value
0        Uganda  2010  1.401
1        Uganda  2011  0.881
2        Uganda  2012  3.551
3        Uganda  2013  1.914
4        Uganda  2014  1.566
5        Uganda  2015    NaN
6        Uganda  2016    NaN
7        Uganda  2017  3.428
8        Uganda  2018    NaN
9        Uganda  2019  2.563
10       Uganda  2020    NaN
11       Uganda  2021  3.416
12       Uganda  2022    NaN
13       Uganda  2023    NaN
14       Uganda  2024    NaN

In [14]:
query5 = """

SELECT "Country Name", "Year", "Value"
FROM eac_indicators
WHERE "Series Name" = 'GDP per capita (current LCU)'
AND "Country Name" = 'Kenya'
AND "Year" BETWEEN 2020 AND 2024
ORDER BY "Year"
"""

result5 = pd.read_sql_query(query5, conn)
result5

  Country Name  Year          Value
0        Kenya  2020  205201.399214
1        Kenya  2021  226002.451823
2        Kenya  2022  248645.715814
3        Kenya  2023  271663.911256
4        Kenya  2024  287500.116953

In [15]:
query6 = """
SELECT "Country Name", COUNT("Value") as data_points
FROM eac_indicators
WHERE "Series Name" = 'Inflation, consumer prices (annual %)'
GROUP BY "Country Name"
ORDER BY data_points ASC
"""

result6 = pd.read_sql_query(query6, conn)
result6

         Country Name  data_points
0  Somalia, Fed. Rep.            0
1    Congo, Dem. Rep.            7
2             Burundi           15
3               Kenya           15
4              Rwanda           15
5         South Sudan           15
6            Tanzania           15
7              Uganda           15

In [16]:
query7 = """
SELECT "Country Name",
       COUNT("Value") as years_with_data,
       AVG("Value") as average_gdp,
       MAX("Value") as highest_gdp,
       MIN("Value") as lowest_gdp
FROM eac_indicators
WHERE "Series Name" = 'GDP per capita (current LCU)'
GROUP BY "Country Name"
ORDER BY average_gdp DESC
"""

result7 = pd.read_sql_query(query7, conn)
result7

,Country Name,years_with_data,average_gdp,highest_gdp,lowest_gdp
0,"Somalia, Fed. Rep.",15,1.154207e+07,1.770127e+07,6.854387e+06
1,Uganda,15,2.759327e+06,4.072926e+06,1.670760e+06
2,Tanzania,15,2.114755e+06,3.082972e+06,1.027963e+06
3,"Congo, Dem. Rep.",15,8.036017e+05,1.833133e+06,3.192443e+05
4,Rwanda,15,6.877974e+05,1.317673e+06,3.461610e+05
5,Burundi,15,5.207059e+05,1.046624e+06,2.667373e+05
6,Kenya,15,1.761513e+05,2.875001e+05,8.648447e+04
7,South Sudan,6,3.913981e+03,4.868059e+03,3.272318e+03

In [18]:
query8 = """
SELECT "Country Name", 
       COUNT("Value") as years_with_data
FROM eac_indicators
WHERE "Series Name" = 'Unemployment, total (% of total labor force) (national estimate)'
GROUP BY "Country Name"
HAVING years_with_data < 10
ORDER BY years_with_data DESC
"""

result8 = pd.read_sql_query(query8, conn)
result8

         Country Name  years_with_data
0              Uganda                8
1            Tanzania                7
2               Kenya                4
3    Congo, Dem. Rep.                3
4  Somalia, Fed. Rep.                2
5             Burundi                2
6         South Sudan                0

In [20]:
# Create two seperate tables from your data

gdp_table = df[df['Series Name'] == 'GDP per capita (current LCU)'][
    ["Country Name", "Year", "Value"]
].rename(columns={"Value": "GDP per capita"})

pop_table = df[df['Series Name'] == 'Population, total'][
    ["Country Name", "Year", "Value"]
].rename(columns={"Value": "Population"})

gdp_table.to_sql('gdp_table', conn, index=False, if_exists='replace')
pop_table.to_sql('pop_table', conn, index=False, if_exists='replace')   

print("GDP rows:", len(gdp_table))
print("Population rows:", len(pop_table))

GDP rows: 120
Population rows: 120

In [21]:
query9 = """
SELECT g."Country Name", 
         g."Year", 
         g."GDP per capita", 
         p."Population"
FROM gdp_table g
JOIN pop_table p
    ON g."Country Name" = p."Country Name" 
    AND g."Year" = p."Year"
ORDER BY g."Country Name", g."Year"
"""

result9 = pd.read_sql_query(query9, conn)
result9

    Country Name  Year  GDP per capita  Population
0        Burundi  2010    2.667373e+05   9376444.0
1        Burundi  2011    2.901348e+05   9717978.0
2        Burundi  2012    3.333613e+05  10071028.0
3        Burundi  2013    3.652049e+05  10439341.0
4        Burundi  2014    3.875138e+05  10799785.0
..           ...   ...             ...         ...
115       Uganda  2020    3.142105e+06  44457152.0
116       Uganda  2021    3.230391e+06  45910930.0
117       Uganda  2022    3.439877e+06  47312719.0
118       Uganda  2023    3.761142e+06  48656601.0
119       Uganda  2024    4.072926e+06  50015092.0

[120 rows x 4 columns]

In [23]:
query10 = """
SELECT 
    "Country Name",
    AVG(Value) AS avg_gdp_per_capita_2020_2024
FROM eac_indicators
WHERE 
    "Series Name" = 'GDP per capita (current LCU)'
    AND Year BETWEEN 2020 AND 2024
    AND Value IS NOT NULL
GROUP BY "Country Name"
ORDER BY avg_gdp_per_capita_2020_2024 DESC
"""

result10 = pd.read_sql_query(query10, conn) 
result10

         Country Name  avg_gdp_per_capita_2020_2024
0  Somalia, Fed. Rep.                  1.539517e+07
1              Uganda                  3.529288e+06
2            Tanzania                  2.801875e+06
3    Congo, Dem. Rep.                  1.382638e+06
4              Rwanda                  1.013762e+06
5             Burundi                  7.673087e+05
6               Kenya                  2.478027e+05

In [24]:
query11 = """
SELECT 
    "Country Name",
    "Year",
    "Value" as expenditure_pct_gdp,
    RANK() OVER (
        PARTITION BY "Year" 
        ORDER BY "Value" DESC
    ) as rank_in_year
FROM eac_indicators
WHERE "Series Name" = 'Gross national expenditure (% of GDP)'
AND "Value" IS NOT NULL
ORDER BY "Year", rank_in_year
"""

result11 = pd.read_sql_query(query11, conn)

# Show only Somalia's ranking across years
somalia_rank = result11[result11["Country Name"] == "Somalia, Fed. Rep."]
somalia_rank

          Country Name  Year  expenditure_pct_gdp  rank_in_year
12  Somalia, Fed. Rep.  2012           149.468846             1
19  Somalia, Fed. Rep.  2013           146.105261             1
26  Somalia, Fed. Rep.  2014           143.375254             1
33  Somalia, Fed. Rep.  2015           142.736195             1
40  Somalia, Fed. Rep.  2016           142.089647             1
46  Somalia, Fed. Rep.  2017           142.582647             1
52  Somalia, Fed. Rep.  2018           145.395656             1
58  Somalia, Fed. Rep.  2019           144.165896             1
64  Somalia, Fed. Rep.  2020           148.388966             1
70  Somalia, Fed. Rep.  2021           146.788991             1
76  Somalia, Fed. Rep.  2022           155.395472             1
82  Somalia, Fed. Rep.  2023           159.244388             1
88  Somalia, Fed. Rep.  2024           167.903401             1

In [28]:
query12 = """
SELECT 
    i."Year",
    i."Value" AS inflation_rate,
    g."Value" AS gdp_per_capita
FROM eac_indicators i
JOIN eac_indicators g
    ON i."Country Name" = g."Country Name"
    AND i."Year" = g."Year"
WHERE i."Series Name" = 'Inflation, consumer prices (annual %)'
AND g."Series Name" = 'GDP per capita (current LCU)'
AND i."Country Name" = 'South Sudan'
AND i."Value" > 50
ORDER BY i."Year"
"""

result12 = pd.read_sql_query(query12, conn)
result12

   Year  inflation_rate  gdp_per_capita
0  2015       52.766330     3893.066489
1  2016      379.999586             NaN
2  2017      187.851630             NaN
3  2018       83.501529             NaN
4  2019       87.241364             NaN
5  2024       91.440822             NaN

In [29]:
query13 = """
SELECT 
    u."Country Name",
    u."Year",
    u."Value" AS unemployment,
    i."Value" AS inflation
FROM eac_indicators u
JOIN eac_indicators i
    ON u."Country Name" = i."Country Name"
    AND u."Year" = i."Year"
WHERE u."Series Name" = 'Unemployment, total (% of total labor force) (national estimate)'
AND i."Series Name" = 'Inflation, consumer prices (annual %)'
AND u."Value" IS NOT NULL
AND i."Value" IS NOT NULL
ORDER BY u."Country Name", u."Year"
"""

result13 = pd.read_sql_query(query13, conn)
result13

        Country Name  Year  unemployment  inflation
0            Burundi  2014         1.572   4.405352
1            Burundi  2020         1.030   7.321106
2   Congo, Dem. Rep.  2012         4.485   9.721828
3   Congo, Dem. Rep.  2016         5.006   2.885851
4              Kenya  2016         2.757   6.297250
5              Kenya  2019         5.014   5.239638
6              Kenya  2021         5.585   6.107936
7              Kenya  2022         5.441   7.659863
8             Rwanda  2012         3.438  10.271018
9             Rwanda  2014         1.169   2.354491
10            Rwanda  2017        11.875   8.279537
11            Rwanda  2018        10.759  -0.311210
12            Rwanda  2019        11.236   3.347877
13            Rwanda  2020        11.829   9.850399
14            Rwanda  2021        15.775  -0.391347
15            Rwanda  2022        15.084  17.689210
16            Rwanda  2023        12.352  19.789547
17            Rwanda  2024        11.331   1.770292
18          Tanzania  2010         1.314   6.200156
19          Tanzania  2011         3.474  12.690969
20          Tanzania  2012         1.437  16.001094
21          Tanzania  2013         2.935   7.870724
22          Tanzania  2014         2.125   6.131614
23          Tanzania  2020         1.792   3.290291
24          Tanzania  2024         2.431   3.056947
25            Uganda  2010         1.401   3.976553
26            Uganda  2011         0.881  16.564350
27            Uganda  2012         3.551  12.679038
28            Uganda  2013         1.914   4.905209
29            Uganda  2014         1.566   3.075707
30            Uganda  2017         3.428   5.209717
31            Uganda  2019         2.563   2.867588
32            Uganda  2021         3.416   2.204572

In [30]:
# Calculate correlation between unemployment and inflation
# For all countries combined
overall_corr = result13["unemployment"].corr(result13["inflation"])
print(f"Overall correlation: {overall_corr:.3f}")

# Correlation by country
country_corr = result13.groupby("Country Name")[["unemployment", "inflation"]].corr()
print("\nCorrelation by country:")
print(result13.groupby("Country Name").apply(
    lambda x: x["unemployment"].corr(x["inflation"])
).round(3))

Overall correlation: 0.083

Correlation by country:
Country Name
Burundi            -1.000
Congo, Dem. Rep.   -1.000
Kenya               0.129
Rwanda              0.168
Tanzania            0.101
Uganda             -0.217
dtype: float64

C:\Users\abdin\AppData\Local\Temp\ipykernel_24472\1420826375.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(result13.groupby("Country Name").apply(

In [31]:
query14 = """
SELECT 
    "Year",
    "Value" AS expenditure,
    LAG("Value") OVER (ORDER BY "Year") AS prev_year_expenditure,
    "Value" - LAG("Value") OVER (ORDER BY "Year") AS annual_change
FROM eac_indicators
WHERE "Series Name" = 'Gross national expenditure (% of GDP)'
AND "Country Name" = 'Somalia, Fed. Rep.'
AND "Value" IS NOT NULL
ORDER BY annual_change DESC
"""

result14 = pd.read_sql_query(query14, conn)
result14

    Year  expenditure  prev_year_expenditure  annual_change
0   2024   167.903401             159.244388       8.659013
1   2022   155.395472             146.788991       8.606481
2   2020   148.388966             144.165896       4.223070
3   2023   159.244388             155.395472       3.848916
4   2018   145.395656             142.582647       2.813009
5   2017   142.582647             142.089647       0.493000
6   2015   142.736195             143.375254      -0.639059
7   2016   142.089647             142.736195      -0.646548
8   2019   144.165896             145.395656      -1.229760
9   2021   146.788991             148.388966      -1.599975
10  2014   143.375254             146.105261      -2.730007
11  2013   146.105261             149.468846      -3.363585
12  2012   149.468846                    NaN            NaN